// Auto-generated configuration from environment variables
// This file is used for local development
// In production, this file is generated by build-config.sh during deployment
window.ENV_CONFIG = {
    BACKEND_URL: 'ws://localhost',
    NODE_ENV: 'development'
};
